M48
; DRILL file {KiCad (5.99.0-10766-geeb405c196)} date Sun Jun 27 17:31:02 2021
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2021-06-27T17:31:02+04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(5.99.0-10766-geeb405c196)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0315
%
G90
G05
T1
X5.4606Y-3.878
X5.4606Y-4.0748
T0
M30
